<script setup lang="ts">
import { marked } from 'marked'

const props = defineProps<{ source: string }>()

const html = computed(() => marked.parse(props.source || '', { async: false }) as string)
</script>

<template>
  <!-- Content is generated by our own AI pipeline for a local single-user app -->
  <!-- eslint-disable-next-line vue/no-v-html -->
  <div
    class="prose prose-sm dark:prose-invert max-w-none"
    v-html="html"
  />
</template>
